[env]
PITCHFORK_WEB_PORT = 19876
'_'.python.venv = { path = ".venv", create = true }

[tools]
age = "latest"
fnox = "latest"
hadolint = "latest"
hk = "latest"
pinact = "latest"
pitchfork = "latest"
pkl = "latest"
